### ISSUE TITLE
XiaoMi-R4A-GB还是不行

### ISSUE THREAD

**Issue by NorthBig** [Plutonium141/XiaoMi-R4A-Gigabit-Actions-OpenWrt#6]
Feedback:
刷了那个sysupgrade的了。还是不行，2022年12月10日购入，买来时候系统是2.30.28. 拆开看了一下闪存芯片是winbond, 处理器是MT7603EN。应该没有什么特殊吧。
通过breed刷入还是不行，打不开192.168.1.1.双蓝灯诡异灰暗。

**Comment by Plutonium141** [comment]
你这个可能是太新了不兼容 也许是因为新版的闪存和旧版的不一样 这个问题我也没有办法

**Comment by MrTaiKe** [comment]
大哥， 
拿去用吧...  
https://github.com/MrTaiKe/Action_OpenWrt_Xiaomi_R4AGv2
https://github.com/MrTaiKe/Action_OpenWrt_Xiaomi_R4AGv2/releases
試試在Github 搜尋 R4AGv2 的對話，能幫助您了解問題解決方法，之前已經累積不少經驗和答案...
祝您好運！

**Comment by NorthBig** [comment]
> https://github.com/MrTaiKe/Action_OpenWrt_Xiaomi_R4AGv2/releases

感谢，[MrTaiKe](https://github.com/MrTaiKe)，好像就是他在做这个V2的。但是不能启动，应该是无限重启，听说是OpenWRT中的flash启动位置跟这个Breed造成的，或者改Breed或者改Openwrt，我都不会。但如果不实用breed直接上传到/tmp文件夹直接刷，你试过没有，我不敢呀。

**Comment by MrTaiKe** [comment]
@NorthBig 
你的應該是v2. 也就是R4AGv2 ，把這裡的對話讀一下。 
https://github.com/acecilia/OpenWRTInvasion/pull/155#issuecomment-1340144419
和我的Readme, 讀一下。 
https://github.com/MrTaiKe/Action_OpenWrt_Xiaomi_R4AGv2
用BREED 可以刷選以下任何一個 sysupgrade
https://github.com/MrTaiKe/Action_OpenWrt_Xiaomi_R4AGv2/releases

我刷 Openwrt-v22.03.2 Kernel_5.10.146 用了很久了， 只有LED燈不管用。 其他正常

Mr.TaiKe
